### ISSUE TITLE
Remove hardcoded intervals

### ISSUE THREAD

**Issue by dajmcdon** [EpiForeSITE/summrt#25]
* `level` is a mandatory arg to the method. This should be used to select the confidence level.
* It may also be nice to allow multiple levels rather than one (but this complicates plotting).

**Comment by kaitejohnson** [comment]
Was thinking about this-- I think we want to make sure that all of the `sumrmt_summary` objects are by default generating the same CI band level (I had assumed they were all 95% CI but now am not sure this was ever verified). I think it makes sense for this to be the default but allow the user to specify.
